# This is a basic workflow to help you get started with Actions

name: Tests/Branch Protections

# Controls when the workflow will run
on:
  # there can be no direct pushes to main or staging
  pull_request:
    branches: [ "main", "staging" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: Main + Staging Branch Protections
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      # Install dependencies
      - name: Install Dependencies
        run: npm install

      - name: Run cypress tests
        run: npm test
      - name: Run eslint 
        run: npm run lint
      - name: Run docs build to ensure no errors
        run: npm run docs
      - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v6.0.0
        env:
          # account will be deleted, don't really care about it being public
          CC_TEST_REPORTER_ID: 4aaddd8457776a6696f6ebf261b5d2a65bac86e6ebbdd8a46f693d5db841d14a
        with:
          coverageCommand: npx nyc report --reporter=text-lcov
